environment:
  matrix:
    - nodejs_version: "10"

init:
- git config --global core.symlinks true

install:
  # Setup the code signing certificate
  - ps: >-
      if (Test-Path Env:\WINDOWS_CERTIFICATE_P12) {
        $workingDirectory = Convert-Path (Resolve-Path -path ".")
        $filename = "$workingDirectory\cert.p12"
        $bytes = [Convert]::FromBase64String($env:WINDOWS_CERTIFICATE_P12)
        [IO.File]::WriteAllBytes($filename, $bytes)
      }
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm ci

cache:
  - '%APPDATA%\npm-cache -> appveyor.yml'

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test

artifacts:
  - path: 'out\make\squirrel.windows\**\*.exe'

build_script:
  - if %APPVEYOR_REPO_TAG% EQU false npm run make
  - if %APPVEYOR_REPO_TAG% EQU true npm run publish
  - if %APPVEYOR_REPO_TAG% EQU true npm run publish -- --arch=ia32
  - ps: Tree ./out/make /F
